prime = [2, 3, 5, 7, 11, 13]
print('prime = [2, 3, 5, 7, 11, 13]')
print('prime[0]:', prime[0])
print('prime[1]:', prime[1])
print('prime[2]:', prime[2])
print('prime[3]:', prime[3])
print('prime[4]:', prime[4])
print('prime[5]:', prime[5])
print('prime[-1]:', prime[-1])
print('prime[-2]:', prime[-2])
print('prime[-3]:', prime[-3])
print('prime[-4]:', prime[-4])
print('prime[-5]:', prime[-5])
print('prime[-6]:', prime[-6])
